apiVersion: apps/v1
kind: Deployment
metadata:
  name: pa-svc-syncker
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: pa-svc-syncker
  template:
    metadata:
      labels:
        k8s-app: pa-svc-syncker
    spec:
      priorityClassName: system-cluster-critical
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      serviceAccountName: pa-svc-syncker
      containers:
      - name: pa-svc-syncker
        image: inwinstack/pa-svc-syncker:v0.7.0
        args:
        - --v=2
        - --logtostderr=true
        - --ignore-namespaces=kube-system,default,kube-public
        - --services=k8s-tcp,k8s-udp