apiVersion: apps/v1
kind: Deployment
metadata:
  name: pa-svc-syncker
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pa-svc-syncker
  template:
    metadata:
      labels:
        app: pa-svc-syncker
    spec:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      serviceAccountName: pa-svc-syncker
      containers:
      - name: pa-svc-syncker
        image: inwinstack/pa-svc-syncker:v0.6.0
        args:
        - --v=2
        - --logtostderr
        - --ignore-namespaces=kube-system,default,kube-public