apiVersion: v1
kind: Service
metadata:
  labels:
    run: nginx
  name: nginx
  namespace: test
spec:
  externalIPs:
  - 172.22.132.160
  ports:
  - name: http-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx
  type: ClusterIP