apiVersion: v1
kind: Service
metadata:
  labels:
    run: nginx
  name: nginx1
  namespace: test
spec:
  type: ClusterIP
  externalIPs:
  - 172.22.132.160
  ports:
  - name: tcp-80
    port: 80
    protocol: TCP
    targetPort: 80
  - name: tcp-8080
    port: 8080
    protocol: TCP
    targetPort: 80
  - name: udp-8080
    port: 8080
    protocol: UDP
    targetPort: 80
  selector:
    run: nginx
